version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: gogotask-profile-db
    ports:
      - 5432:5432
    # volumes:
    #   - ./init:/docker-entrypoint-initdb.d
    #   - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=dshestapalau
      - POSTGRES_DB=gogotask-profile
      
# volumes:
#   data: